### ISSUE TITLE
"INITIALISING K8S RESOURCES" not working on mac

### ISSUE THREAD

**Issue by iptizer** [wuestkamp/cka-example-environments#1]
I had problems with executing `./up.sh` in the stage *INITIALISING K8S RESOURCES*.

One solution may be to use the following instead of the `ssh-keygen...`:

```bash
vagrant ssh cluster1-master1 -c "sudo su - root -c 'kubectl apply -f /vagrant/k8s/init.yaml'"
```

Do you think this makes sense? Would a PR be accepted?

**Comment by wuestkamp** [comment]
I'm using Mac as well and had no issues. What was the error?
Feel free to create a PR as your solution looks fine to me and it might be better to just rely on vagrant. Thanks

**Comment by iptizer** [comment]
MIght also be related to VirtualBox 6 or Vagrant, but somehow the 192.168 network is not connected.
Did not dig deeper as the vagrant solution worked. PR on the way.
